function H = hessian(in1)
%HESSIAN
%    H = HESSIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Aug-2022 20:26:13

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = -q3;
t3 = -q4;
t4 = q1+t2;
t5 = q2+t3;
t6 = abs(t4);
t7 = abs(t5);
t8 = 0;%dirac(t4);
t9 = 0;%dirac(t5);
t10 = sign(t4);
t11 = sign(t5);
t12 = t6.^2;
t13 = t7.^2;
t14 = t10.^2;
t15 = t11.^2;
t16 = t12+t13;
t17 = 1.0./sqrt(t16);
t18 = t17.^3;
t19 = t14.*t17;
t20 = t15.*t17;
t23 = t6.*t8.*t17.*2.0;
t24 = t7.*t9.*t17.*2.0;
t21 = -t19;
t22 = -t20;
t25 = -t23;
t26 = -t24;
t27 = t12.*t14.*t18;
t28 = t13.*t15.*t18;
t31 = t6.*t7.*t10.*t11.*t18;
t29 = -t27;
t30 = -t28;
t32 = -t31;
t35 = t21+t25+t27;
t36 = t22+t26+t28;
t33 = t19+t23+t29;
t34 = t20+t24+t30;
H = reshape([t33,t32,t35,t31,t32,t34,t31,t36,t35,t31,t33,t32,t31,t36,t32,t34],[4,4]);
